[package]
name = "rustcc_ast"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
rustcc_source.path = "../rustcc_source"

[lints]
workspace = true
