[workspace]
resolver = "2"
members = ["rustcc-driver", "rustcc", "test-driver"]

[workspace.package]
authors = ["AMS21 <ams21.github@gmail.com>"]
edition = "2024"
license = "MIT"
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
assert_cmd = "2.0.16"
clap = "4.5.31"
colored = "3.0.0"
