[package]
name = "rustcc-compiler"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
default-run = "rustcc"

[[bin]]
name = "rustcc"
path = "src/main.rs"

[features]
default = ["color"]
color = ["rustcc_driver/color"]

[dependencies]
rustcc_driver = { path = "../rustcc_driver", default-features = false }

[dev-dependencies]
assert_cmd.workspace = true

[lints]
workspace = true
