[package]
name = "rustcc-compiler"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
default-run = "rustcc"

[[bin]]
name = "rustcc"
path = "src/main.rs"

[dependencies]
rustcc_driver = { path = "../rustcc_driver" }

[dev-dependencies]
anstream.workspace = true
anstyle.workspace = true
assert_cmd.workspace = true
similar.workspace = true
tempfile.workspace = true

[lints]
workspace = true
