[package]
name = "rustcc-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "fuzz_compile"
path = "fuzz_targets/fuzz_compile.rs"
test = false
doc = false
bench = false

[dependencies]
libfuzzer-sys = "0.4.13"
rustcc_codegen.path = "../crates/rustcc_codegen"
rustcc_diagnostic.path = "../crates/rustcc_diagnostic"
rustcc_lexer.path = "../crates/rustcc_lexer"
rustcc_parser.path = "../crates/rustcc_parser"
rustcc_source.path = "../crates/rustcc_source"

[profile.release]
codegen-units = 1
lto = "thin"
