[package]
name = "rustcc_driver"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
clap.workspace = true
rustcc_codegen.path = "../rustcc_codegen"
rustcc_diagnostic.path = "../rustcc_diagnostic"
rustcc_lexer.path = "../rustcc_lexer"
rustcc_llvm.path = "../rustcc_llvm"
rustcc_parser.path = "../rustcc_parser"
rustcc_source.path = "../rustcc_source"

[lints]
workspace = true
