[package]
name = "rustcc_lexer"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["color"]
color = ["rustcc_diagnostic/color"]

[dependencies]
pastey.workspace = true
phf.workspace = true
rustcc_ast = { path = "../rustcc_ast" }
rustcc_diagnostic = { path = "../rustcc_diagnostic", default-features = false }
rustcc_source = { path = "../rustcc_source" }

[lints]
workspace = true
