[package]
name = "test-driver"
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
assert_cmd.workspace = true
clap.workspace = true
colored.workspace = true
regex.workspace = true
