[package]
name = "rustcc_llvm"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
doctest = false

[dependencies]
semver.workspace = true

[build-dependencies]
bindgen.workspace = true
semver.workspace = true

[lints]
workspace = true
