name: Rust

on:
  pull_request:
    paths:
      # Workflow file itself
      - '.github/workflows/rust.yml'
      # Rust files
      - '**.rs'
      # C files
      - '**.c'
      - '**.h'
      # Cargo files
      - 'Cargo.lock'
      - 'Cargo.toml'
      # Configuration files
      - '.rustfmt.toml'
      - '.clippy.toml'
  push:
    paths:
      # Workflow file itself
      - '.github/workflows/rust.yml'
      # Rust files
      - '**.rs'
      # C files
      - '**.c'
      - '**.h'
      # Cargo files
      - 'Cargo.lock'
      - 'Cargo.toml'
      # Configuration files
      - '.rustfmt.toml'
      - '.clippy.toml'
  workflow_dispatch:

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}-${{github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  LLVM_VERSION: 21
  LLVM_VERSION_MACOS: 22

defaults:
  run:
    shell: bash

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Audit Rust Dependencies
      uses: actions-rust-lang/audit@v1

  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy

    - name: Install cargo-hack
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - name: Install LLVM tools
      uses: ZhongRuoyu/setup-llvm@v0
      with:
        llvm-version: ${{ matrix.os == 'macos-latest' && env.LLVM_VERSION_MACOS || env.LLVM_VERSION }}

    - name: Clippy
      run: cargo hack clippy --workspace --feature-powerset --verbose -- -D warnings

  formatting:
    runs-on: ubuntu-slim

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt

    - name: Rustfmt Check
      uses: actions-rust-lang/rustfmt@v1

  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Install LLVM tools
      uses: ZhongRuoyu/setup-llvm@v0
      with:
        llvm-version: ${{ env.LLVM_VERSION }}

    - name: Build documentation
      env:
        RUSTDOCFLAGS: -D warnings
      run: cargo doc --workspace --all-features --no-deps --document-private-items

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - macos-26-intel
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest

        toolchain:
          - nightly
          - stable
          - "1.88" # MSRV

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}

    - name: Install cargo-hack
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - name: Install LLVM tools
      uses: ZhongRuoyu/setup-llvm@v0
      with:
        llvm-version: ${{ matrix.os == 'macos-latest' && env.LLVM_VERSION_MACOS || env.LLVM_VERSION }}

    - name: Build
      run: cargo build --workspace --verbose

    - name: Run tests
      run: cargo hack test --workspace --feature-powerset --verbose

  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly

    - name: Install LLVM tools
      uses: ZhongRuoyu/setup-llvm@v0
      with:
        llvm-version: ${{ env.LLVM_VERSION }}

    - name: Install tarpaulin
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-tarpaulin

    - name: Run cargo-tarpaulin
      run: cargo tarpaulin --verbose --workspace --all-targets --all-features --follow-exec --locked --post-test-delay 2 --out Xml --engine llvm

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

  careful:
    runs-on: ${{ matrix.os }}

    env:
      ASAN_OPTIONS: "detect_stack_use_after_return=1"

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm

        flags:
          - ""
          - "-Zcareful-sanitizer=address"
          - "-Zcareful-sanitizer=leak"
          - "-Zcareful-sanitizer=thread"

        include:
          - os: macos-latest
            flags: ""
          - os: macos-26-intel
            flags: ""

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly

    - name: Install cargo-hack
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - name: Install cargo-careful
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-careful

    - name: Install LLVM tools
      uses: ZhongRuoyu/setup-llvm@v0
      with:
        llvm-version: ${{ matrix.os == 'macos-latest' && env.LLVM_VERSION_MACOS || env.LLVM_VERSION }}

    - name: Build
      run: cargo careful build --workspace --verbose ${{ matrix.flags }}

    - name: Run tests
      run: cargo hack careful test --workspace --feature-powerset --verbose ${{ matrix.flags }}

  unused-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install cargo-shear
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-shear

    - name: Check for unused dependencies
      run: cargo shear

  unused-features:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install cargo-features-manager
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-features-manager

    - name: Check for unused features
      run: cargo features prune --no-tmp
